// Items (Core Rulebook ch.4 "Loot" and character creation). Server-side only: players can look up an item by
// exact name, only admins can list them. `slot` is the gear slot for wearables.

export const ITEMS = [
  // consumables
  { name: 'Healing Potion', type: 'Consumable', effect: 'Heals 5 HB slots', page: 216 },
  { name: 'Good Healing Potion', type: 'Consumable', effect: 'Heals 6 HB slots', page: 216 },
  {
    name: 'Gold Standard Healing Potion',
    type: 'Consumable',
    effect: 'Heals 7 HB slots and mends one Minor Injury',
    page: 217,
  },
  {
    name: 'Supreme Healing Potion',
    type: 'Consumable',
    effect: 'Heals 8 HB slots and mends one Minor or Major Injury; or 8d8 Holy damage to an undead Mob',
    page: 217,
  },
  {
    name: 'Heal Severe Injury Potion',
    type: 'Consumable',
    effect: 'Heals 9 HB slots and mends all Injuries',
    page: 218,
  },
  { name: 'Heal Pet Potion', type: 'Consumable', effect: 'Heals a pet 5 HB slots', page: 216 },
  {
    name: 'Mana Potion',
    aliases: ['Standard Mana Potion'],
    type: 'Consumable',
    effect: 'Fully restores Mana (1 Action to drink)',
    page: 216,
  },
  {
    name: 'Good Mana Refill Potion',
    type: 'Consumable',
    effect: 'Restores 15 Mana per round for 10 rounds',
    page: 217,
  },
  {
    name: 'Bandage',
    aliases: ['Bandages'],
    type: 'Consumable',
    effect: 'Spend an Action to remove Blood Trail',
    page: 216,
  },
  {
    name: 'Poison Antidote',
    aliases: ['Antidote', 'Poison Antidotes'],
    type: 'Consumable',
    effect: 'Cures Poisoned',
    page: 216,
  },
  {
    name: 'Torch',
    aliases: ['Torches'],
    type: 'Consumable',
    effect: 'Bright light 20 ft, dim light 20 ft more; burns about an hour',
    page: 216,
  },
  { name: 'Crawler Biscuits', aliases: ['Crawler Biscuit'], type: 'Consumable', effect: 'Food', page: 216 },
  {
    name: 'Basic Dynamite',
    aliases: ['Stick of Basic Dynamite', 'Dynamite'],
    type: 'Explosive',
    effect: '1d6 Bludgeoning, 0 ft Blast radius + 5 ft Splash',
    page: 216,
  },
  {
    name: 'Good Goblin Dynamite',
    aliases: ['Stick of Good Goblin Dynamite', 'Goblin Dynamite'],
    type: 'Explosive',
    effect: '2d6 Bludgeoning, 5 ft Blast radius + 5 ft Splash',
    page: 217,
  },
  {
    name: 'Jug O’ Boom',
    aliases: ["Jug O' Boom", 'Carl’s Jug O’ Boom'],
    type: 'Explosive',
    effect: '1d8 Fire, 5 ft Blast radius + 15 ft Splash; Burned if 1+ HB slot lost',
    page: 183,
  },
  { name: 'Hob-Lobber', aliases: ['Hob-Lobbers'], type: 'Explosive', effect: '3d6 Piercing, +10 ft Splash', page: 183 },
  {
    name: 'Goblin Smoke Bomb',
    type: 'Explosive',
    effect:
      'Multicolor smoke 30 ft around impact for up to 3 minutes (1 in a breeze); attacks into/out of it have Disadvantage',
    page: 184,
  },
  {
    name: 'Medicine or Lube? Scratcher',
    aliases: ['Medicine or Lube Scratcher'],
    type: 'Consumable',
    effect: 'Action: roll 1d2 — 1: a target within 20 ft is Staggered; 2: target gets a Rank 15 Heal Others',
    cooldown: '30 minutes',
    page: 218,
  },
  {
    name: 'Nebular Roulette Scratcher',
    type: 'Consumable',
    effect: 'Action: roll 1d6 — 1: you take 2d12+F Electric; 2–6: the target takes it',
    cooldown: '30 minutes',
    page: 218,
  },
  { name: 'Potion of +1 Skill', type: 'Consumable', effect: '+1 Rank in a Skill (permanent)', page: 216 },
  { name: 'Potion of +2 Skill', type: 'Consumable', effect: '+2 Ranks in a Skill (permanent)', page: 217 },
  { name: 'Potion of +3 Skill', type: 'Consumable', effect: '+3 Ranks in a Skill (permanent)', page: 217 },
  { name: 'Potion of +5 Skill', type: 'Consumable', effect: '+5 Ranks in a Skill (permanent)', page: 218 },
  { name: 'Scroll of Upgrade', type: 'Consumable', effect: 'Upgrades your signature weapon (Table 26)', page: 117 },
  {
    name: 'Neighborhood Map',
    type: 'Map',
    effect: 'Adds the Neighborhood and its Mobs to your minimap; +1 h credit when grinding 5+ h',
    page: 215,
  },
  {
    name: 'Borough Field Guide',
    type: 'Map',
    effect: 'Outlines the borough’s quadrants with Mob level ranges; +2 h credit when grinding 5+ h',
    page: 215,
  },
  // mundane
  { name: 'Rope', type: 'Mundane', effect: '50 feet', page: 216 },
  // sample magical gear
  { name: 'Bitch-Ass Buckler', type: 'Gear', slot: 'Hands/Holding', effect: '+1 Shield Block, +3 DR', page: 217 },
  {
    name: 'Bernie Boots',
    type: 'Gear',
    slot: 'Feet',
    effect: 'While Dying you can still Move and read movement-related HUD messages',
    page: 217,
  },
  { name: 'Big Purple Plume', type: 'Gear', slot: 'Accessory', effect: '+2 Charisma', page: 217 },
  {
    name: 'Friendship Bracelet',
    aliases: ['Friendship Bracelet of [Race]kind'],
    type: 'Gear',
    slot: 'Accessory',
    effect:
      'Mobs and NPCs of one Race (1d10: dwarven, elven, fairy, orc, skyfowl) aren’t automatically hostile. Remove or break it and they are hostile for the rest of the floor',
    page: 217,
  },
  {
    name: 'Enchanted Elbow Pads of the Elbow-Walking Turkeys',
    type: 'Gear',
    slot: 'Arms',
    effect: '+2 DR, +2 Dexterity',
    page: 217,
  },
  {
    name: 'Skullcap of Sucking',
    type: 'Gear',
    slot: 'Head',
    effect: '+1 DR; gain 1 AI Favor on each Critical Fail',
    page: 217,
  },
  {
    name: 'Tough Guy Tattoo',
    type: 'Gear',
    slot: 'Accessory',
    effect: '+3 Constitution; add 10 to your 100% HB slot',
    page: 217,
  },
  {
    name: 'Selfie Stick of the Self-Mutilator',
    type: 'Gear',
    slot: 'Hands/Holding',
    effect:
      '1 fewer HB slot while held. Enter combat with a Minor Injury: +1 Popularity (Major: +2) and that many extra Actions each round',
    page: 218,
  },
  {
    name: 'Chesty Cheese Grater',
    type: 'Gear',
    slot: 'Torso',
    effect: '+2 DR, +5% Constitution, Damage Reflection 3:1 vs melee',
    page: 218,
  },
  {
    name: 'Enchanted Leggings of Insanity',
    type: 'Gear',
    slot: 'Legs',
    effect: '+1 DR, +3 Escape Artist; fit your lower body through any opening',
    page: 218,
  },
  {
    name: 'Enchanted Cloak of the Slippery Perv',
    type: 'Gear',
    slot: 'Accessory',
    effect: '+6 Charisma; +3 Evade Buff with a new accusation against your attacker',
    page: 218,
  },
  {
    name: 'Enchanted Wand of Incontinence',
    type: 'Gear',
    slot: 'Hands/Holding',
    effect: '+10% Constitution; once per session (Action) a creature within 30 ft voids its bowels and is Fatigued',
    page: 218,
  },
  {
    name: 'Hand Grips of Hella Holding',
    type: 'Gear',
    slot: 'Hands/Holding',
    effect: '+10% Strength, +3 DR; your grip can’t be broken',
    page: 218,
  },
  {
    name: 'Borant Corporation Reset Button',
    type: 'Gear',
    slot: 'Accessory',
    effect: 'Once per floor restart the current scene (up to 10 minutes in; first round in combat)',
    page: 219,
  },
  {
    name: 'Beret of Divine Intervention',
    type: 'Gear',
    slot: 'Head',
    effect: 'Max one Skill at Rank 15; double personal rewards near a deity (triple near your own)',
    page: 219,
  },
  {
    name: 'The Sassy Stiletto',
    type: 'Gear',
    slot: 'Hands/Holding',
    effect: '+5 all Stats, Dagger at Rank 15, crits on 16–20, intelligent (free Look for Clues with Perception 10)',
    page: 219,
  },
];
