// Spells (Core Rulebook ch.4, pp. 202–214). Server-side only: players can look up a spell by its exact
// name, but only admins can list them, so unknown spells aren't spoiled.
// Effects are short summaries; upgrades use compact notation. Spells use Int to hit/damage unless `stat` says otherwise.

const S = (o) => ({ stat: 'int', ...o });

export const SPELLS = [
  S({
    name: 'Air Buddy',
    subtype: 'passive',
    tags: 'Favored: Mage',
    manaCost: '12',
    range: 'Self',
    effect:
      'Launch yourself up to 10 × Int Mod ft and land safely on solid ground (otherwise you fall). Cast twice in a row to double jump',
    upgrades: 'R5: bring 1 willing target your size · R10: up to 20 × Int Mod ft · R15: bring up to 5 targets',
    page: 202,
  }),
  S({
    name: 'Astral Paw',
    aliases: ['Astral Hand', 'Astral Claw'],
    subtype: 'passive',
    manaCost: '12',
    range: '30 feet',
    duration: 'Until end of combat or 5 minutes',
    effect:
      'Conjure a spectral paw that manipulates objects up to 30 ft away (1 Action). Skill Checks through it have Disadvantage',
    upgrades:
      'R5: Pugilism/Slice Attacks with it add 1 Rank damage die · R10: up to 4 sizes larger, range 50 ft · R15: no Disadvantage, lasts 15 min',
    page: 203,
  }),
  S({
    name: 'Bad Faith',
    subtype: 'attack',
    stat: 'cha',
    tags: 'Necrotic · Favored: Cleric',
    manaCost: '10',
    range: '40 feet',
    baseDamage: '1d8 + Cha Necrotic',
    upgrades: 'R5: +1d8, +5 ft Splash · R10: +1d8, ends all Buffs on victims for the combat · R15: +1d8, +5 ft Splash',
    page: 203,
  }),
  S({
    name: 'Bang Bro',
    subtype: 'passive',
    manaCost: '5',
    range: '5 feet',
    duration: '5 minutes + 1 minute per Rank',
    cooldown: '15 minutes',
    effect: 'Enchant a weapon you hold: +2 mixed Fire and Electric damage',
    upgrades: 'R5: +1d6 Fire/Electric · R10: +1d6, Burned on Amazing Success · R15: +1d6, Shocked on Amazing Success',
    page: 203,
  }),
  S({
    name: 'Clockwork Triplicate',
    subtype: 'passive',
    manaCost: '26',
    range: '5 feet',
    duration: '1 minute per Rank',
    limitations: 'Only castable on pets and minions',
    effect:
      'Your pet or minion splits into three with all its abilities. Commanding each copy takes an Action and an Unopposed Animal Handling check',
    upgrades: 'R5: 2 min per Rank · R10: 3 min per Rank · R15: copies follow your commands to the original',
    page: 203,
  }),
  S({
    name: 'Confusing Fog',
    subtype: 'passive',
    manaCost: '6',
    range: '40 feet',
    duration: '2 full rounds or 20 seconds',
    cooldown: '15 minutes',
    effect: '25 × 25 ft fog your side can see through; Mobs attack targets inside with Disadvantage',
    upgrades: 'R5: 50 × 50 ft, 1 min · R10: 100 × 100 ft, 5 min · R15: 500 × 500 ft, 15 min',
    page: 204,
  }),
  S({
    name: 'Dirt Clod',
    subtype: 'attack',
    tags: 'Bludgeoning',
    manaCost: '1',
    range: '100 feet',
    aiFavor: '2',
    baseDamage: '1d2 + Int Bludgeoning',
    upgrades: 'R5: +2d2 · R10: +1d2, Woozy · R15: +1d2, +1 Rank damage die',
    page: 204,
  }),
  S({
    name: 'Drain Life',
    subtype: 'attack',
    tags: 'Necrotic',
    manaCost: '14',
    range: '30 feet',
    baseDamage: '1d6 + Int Necrotic',
    upgrades:
      'R5: +1d6, heal 1 HB slot if the target loses 3+ slots · R10: +1d6, heal +1 more · R15: +1d6, heal +1 more',
    page: 204,
  }),
  S({
    name: 'Earworm',
    subtype: 'attack',
    stat: 'cha',
    tags: 'Sonic · Favored: Bard',
    manaCost: '6',
    range: '30 feet',
    cooldown: 'Once per round',
    baseDamage: '1d6 + Cha Sonic',
    upgrades: 'R5: +1d6 · R10: +1d6, Queasy · R15: +1d6, +10 ft Splash',
    page: 204,
  }),
  S({
    name: 'Fear',
    subtype: 'attack',
    tags: 'Mind Control',
    manaCost: '3',
    range: '25 feet',
    limitations: 'Scary Mobs are immune (GM’s call)',
    effect:
      'Target a non-Boss Mob of half your level or less. Standard Success: it loses its Dex Mod for the combat. Better: it spends two Actions next round running away',
    upgrades: 'R5: +5 ft Blast radius · R10: +5 ft, Paralyzed on a Critical Hit · R15: +5 ft',
    page: 204,
  }),
  S({
    name: 'Fireball',
    subtype: 'attack',
    tags: 'Fire · Area of Effect',
    manaCost: '45',
    range: '80 feet',
    cooldown: 'Once per scene',
    limitations:
      'Attack roll has Disadvantage (slow). On a miss roll 1d8 for direction; it lands as many ft away as you missed by',
    baseDamage: '1d12 + Int Fire, 10 ft Blast radius',
    upgrades:
      'R5: +1d12, Burned if 1+ HB slot lost · R10: +1d12, becomes an 80 ft Line (keeps the Blast) · R15: +1d12, +40 ft Splash',
    page: 205,
  }),
  S({
    name: 'Fire Fingers',
    subtype: 'attack',
    tags: 'Fire',
    manaCost: '3',
    range: 'Melee',
    aiFavor: '1',
    baseDamage: '1d4 + Int Fire',
    upgrades:
      'R5: +1d4 · R10: +1d4, Burned · R15: +1d4, Pugilism/Unarmed/Slice strikes add a Fire Fingers Rank damage die',
    page: 205,
  }),
  S({
    name: 'Frost Scar',
    subtype: 'attack',
    tags: 'Ice',
    manaCost: '2',
    range: 'Melee',
    aiFavor: '1',
    baseDamage: '1d4 + Int Ice',
    upgrades: 'R5: +1d4, target can’t heal itself next round · R10: +1d4, Stiff Legs · R15: +1d4, The Taint',
    page: 205,
  }),
  S({
    name: 'Grand Illusion',
    subtype: 'passive',
    tags: 'Intelligence',
    manaCost: '7',
    range: '40 feet',
    duration: '2 minutes',
    cooldown: '15 minutes',
    effect:
      'Create an illusion. One Int-Opposed Spell Check vs everyone who sees it (Advantage for simple, Disadvantage for complex ones); on Success they believe it',
    upgrades: 'R5: believers gain Woozy (or similar) · R10: also Queasy · R15: also Shocked',
    page: 205,
  }),
  S({
    name: 'Heal',
    subtype: 'passive',
    stat: 'none',
    tags: 'Heal · Interrupt',
    manaCost: '2',
    range: 'Self only',
    limitations: 'Rank 1 maximum',
    effect: 'Heal 2 Health Bar slots',
    upgrades: 'None',
    page: 206,
  }),
  S({
    name: 'Heal Critter',
    subtype: 'passive',
    stat: 'none',
    tags: 'Heal · Interrupt',
    manaCost: '8',
    range: '30 feet',
    limitations: 'Only pets and minions',
    effect: 'Target heals to 100% Health Bar',
    upgrades: 'R5: mends a Minor Injury · R10: mends a Major Injury · R15: regrows lost appendages',
    page: 206,
  }),
  S({
    name: 'Heal Others',
    subtype: 'passive',
    stat: 'none',
    tags: 'Heal · Interrupt',
    manaCost: '6',
    range: '30 feet',
    limitations: 'Not on yourself, pets or minions',
    effect: 'Target heals 1d4 HB slots',
    upgrades: 'R5: 1d6 slots · R10: 2d6 slots · R15: all party members in a 20 ft Burst',
    page: 206,
  }),
  S({
    name: 'Heal Self',
    subtype: 'passive',
    stat: 'none',
    tags: 'Heal · Interrupt',
    manaCost: '1',
    range: 'Self only',
    effect: 'Heal 1d4 HB slots',
    upgrades:
      'R5: 1d6 slots, mend a Minor Injury, Poison or Disease · R10: 2d6 slots, mend a Major Injury or other Debuff · R15: heal to full + short rest benefits',
    page: 206,
  }),
  S({
    name: 'Hole',
    subtype: 'passive',
    manaCost: '12',
    range: '10 feet',
    duration: 'Until end of combat or 5 minutes',
    limitations: 'Not on saferoom doors or living things',
    effect: 'Temporary 2 ft wide hole, 1 inch deep per Rank, in a surface or material',
    upgrades:
      'R5: can make it narrower · R10: widen 1 inch per inch of depth given up · R15: end it with a thought, destroying anything inside',
    page: 207,
  }),
  S({
    name: 'Holy Aura',
    subtype: 'attack',
    stat: 'cha',
    tags: 'Holy · Area of Effect · Favored: Cleric & Paladin',
    manaCost: '7',
    range: '5 ft Burst radius',
    cooldown: 'Once per round',
    effect: 'Hurts only enemies around you',
    baseDamage: '1d4 + Cha Holy, 5 ft Burst radius',
    upgrades: 'R5: +1d4, double damage to undead · R10: +1d4, +5 ft Burst · R15: +1d4, +5 ft Burst',
    page: 207,
  }),
  S({
    name: 'Hot Stuff Aura',
    subtype: 'passive',
    tags: 'Area of Effect · Favored: Bard',
    manaCost: '8',
    range: '5 ft Burst radius',
    duration: '2 rounds',
    cooldown: '5 minutes',
    effect:
      'Shield for you and allies in range: HB slots equal to your Cha Mod, 2 in each, vs all damage. Can’t be healed',
    upgrades: 'R5: 4 per slot · R10: +5 ft Burst, 6 per slot · R15: +10 ft Burst, 8 per slot',
    page: 207,
  }),
  S({
    name: 'Ice Blast',
    subtype: 'attack',
    tags: 'Ice',
    manaCost: '9',
    range: '40 feet',
    baseDamage: '1d8 + Int Ice',
    upgrades: 'R5: +1d8 · R10: +1d8, push 10 ft · R15: +1d8, can be a 15 ft Cone',
    page: 207,
  }),
  S({
    name: 'Icicles',
    subtype: 'attack',
    tags: 'Ice',
    manaCost: '19',
    range: '60 feet',
    baseDamage: '1d12 + Int Ice',
    upgrades: 'R5: +1d12 · R10: +1d12, Stiff Legs · R15: +1d12, Armor-Piercing',
    page: 207,
  }),
  S({
    name: 'Intimate Touches',
    subtype: 'passive',
    stat: 'none',
    tags: 'Heal · Favored: Cleric & Paladin',
    manaCost: '8',
    range: '5 feet',
    limitations: 'Not an Interrupt',
    effect: 'Target (can be you) heals HB slots equal to your Cha Mod',
    upgrades: 'R5: also heals a Minor Injury · R10: also a Major Injury · R15: also all Poison & Disease',
    page: 208,
  }),
  S({
    name: 'Lightning Bolt',
    subtype: 'attack',
    tags: 'Electric',
    manaCost: '15',
    range: '100 feet',
    baseDamage: '1d10 + Int Electric',
    upgrades:
      'R5: +1d10 · R10: +1d10, 100 ft Line · R15: +1d10, forks to any targets within 15 ft of the previous one (half damage each)',
    page: 208,
  }),
  S({
    name: 'Magic Missile',
    subtype: 'attack',
    tags: 'Force',
    manaCost: '5',
    range: 'Line of sight',
    aiFavor: '1',
    baseDamage: '1d4 + Int Force',
    upgrades:
      'R5: +1d4, variable cost (3 Mana −4 dmg, 4 Mana −2, 6 Mana +1 Rank die) · R10: +1d4, Force + Fire and Burned · R15: base damage ×3',
    page: 208,
  }),
  S({
    name: 'Mind Tickle',
    subtype: 'attack',
    stat: 'cha',
    tags: 'Psychic · Favored: Cleric',
    manaCost: '2',
    range: '40 feet',
    aiFavor: '2',
    baseDamage: '1d2 + Cha Psychic',
    upgrades: 'R5: +1d2 · R10: +1d2, Sore as Shit · R15: +1d2, Muted',
    page: 208,
  }),
  S({
    name: 'Minion Army',
    subtype: 'passive',
    tags: 'Intelligence · Area of Effect · Mind Control',
    manaCost: '50',
    range: '50 ft Burst radius',
    duration: '2 minutes',
    cooldown: '5 hours',
    limitations: '5-minute casting time without moving; only Mobs with Intelligence 2+',
    effect: 'Standard Success: 1 in 50 Mobs in the area (min 1) fight for you; more on higher successes',
    upgrades: 'R5: 4 min cast, 5 min duration · R10: + Charisma to radius, 10 min · R15: + Charisma to radius, 15 min',
    page: 209,
  }),
  S({
    name: 'Nature’s Breath',
    subtype: 'passive',
    stat: 'none',
    tags: 'Heal · Interrupt · Favored: Druid',
    manaCost: '6',
    range: '5 feet',
    effect: 'Target (you, a pet or minion too) heals HB slots equal to a Nature’s Breath Rank damage die roll',
    upgrades: 'R5: +1 to the roll · R10: +1, removes a Minor Injury · R15: +1, removes a Major Injury',
    page: 209,
  }),
  S({
    name: 'Oakhide',
    subtype: 'passive',
    tags: 'Favored: Druid',
    manaCost: '5',
    range: 'Self',
    duration: '2 minutes',
    cooldown: '10 minutes',
    effect: '+2 Damage Resistance',
    upgrades: 'R5: +2 DR, 3 min · R10: +2 DR, can target allies within 10 ft · R15: +2 DR, 4 min',
    page: 209,
  }),
  S({
    name: 'Paladin’s Smite',
    subtype: 'attack',
    stat: 'cha',
    tags: 'Holy · Favored: Paladin',
    manaCost: '11',
    range: '30 feet',
    baseDamage: '1d8 + Cha Holy',
    upgrades: 'R5: +1d8 · R10: +1d8, Take Down · R15: +1d8, Armor-Piercing',
    page: 209,
  }),
  S({
    name: 'Panty Dropper',
    subtype: 'passive',
    stat: 'cha',
    tags: 'Charisma · Mind Control · Favored: Bard',
    manaCost: '10',
    range: '10 feet',
    duration: '2 minutes or until you finish',
    cooldown: '5 minutes',
    effect: 'Int-Opposed Spell Check vs a non-Boss; on Success it stops fighting and only wants you',
    upgrades: 'R5: 5 min · R10: 10 min · R15: 15 min',
    page: 209,
  }),
  S({
    name: 'Ping',
    subtype: 'passive',
    tags: 'Area of Effect',
    manaCost: '5',
    range: '1 mile Burst radius',
    cooldown: '5 minutes',
    effect:
      'Reveals distance and location of non-crawlers and non-red-tagged Mobs around you ("somewhat complete" info)',
    upgrades:
      'R5: cast a known Fear on all eligible Mobs in range for its Mana only · R10: obstacles don’t reduce range, "mostly complete" · R15: Fear costs nothing, "entirely complete"',
    page: 210,
  }),
  S({
    name: 'Protective Shell',
    subtype: 'passive',
    stat: 'none',
    tags: 'Interrupt · Area of Effect',
    manaCost: 'None',
    range: '10 ft Burst radius',
    duration: '5 seconds',
    cooldown: '30 hours',
    limitations: 'Must be imbued onto something you wear; the shell can’t move',
    effect:
      '10 + Int ft shell around you and party: pushes Mobs out, they can’t enter or physically attack inside (magic still works)',
    upgrades:
      'R5: 10 s, blocks non-Spell attacks from outside this round · R10: 20 s / 2 rounds · R15: 30 s / 3 rounds',
    page: 210,
  }),
  S({
    name: 'Puddle Jumper',
    subtype: 'passive',
    manaCost: '20',
    range: 'Line of sight to a surface',
    cooldown: '5 hours',
    limitations: '10-second delay before it happens',
    effect: 'Teleport you and up to 3 party members',
    upgrades:
      'R5: 2 s delay, any destination · R10: 1 s, anywhere within 1,000 yards unseen · R15: no delay, within 1 mile',
    page: 210,
  }),
  S({
    name: 'Rise, Dead Minion!',
    subtype: 'attack',
    tags: 'Favored: Necromancer',
    manaCost: '10',
    range: '30 feet',
    duration: '1 round',
    effect: 'A Medium skeleton rises and makes a melee attack, then collapses into difficult terrain',
    baseDamage: '1d8 + Int Necrotic',
    upgrades: 'R5: attacks twice · R10: Large, 10 ft reach, +1d8 · R15: Colossal, 15 ft reach, +1 Rank damage die',
    page: 211,
  }),
  S({
    name: 'Rootfoot',
    subtype: 'attack',
    tags: 'Favored: Druid',
    manaCost: '5',
    range: '30 feet',
    duration: '2 rounds',
    effect: 'On Success a victim up to Medium (4) is Held; escape Difficulty uses this Spell’s Rank instead of Str',
    upgrades: 'R5: up to Large, 3 rounds · R10: up to Huge, 4 rounds · R15: up to Colossal, also Poisoned',
    page: 211,
  }),
  S({
    name: 'Second Chance',
    subtype: 'passive',
    manaCost: '10',
    range: '10 feet',
    duration: '1 minute',
    effect:
      'Raise a dead Mob of lower level as your Undead Minion with half its HB slots. 1 Action to command, then it acts on its own',
    upgrades: 'R5: up to 5 levels higher, 5 min · R10: 10 levels higher, 15 min · R15: 15 levels higher, 45 min',
    page: 211,
  }),
  S({
    name: 'Shield',
    subtype: 'passive',
    stat: 'none',
    tags: 'Interrupt',
    manaCost: '8',
    range: 'Self',
    duration: '5 minutes',
    effect: 'Force field with 2 HB slots of your Con Mod each that absorbs non-magic damage first. Can’t be healed',
    upgrades: 'R5: 5 slots · R10: 10 slots · R15: 15 slots',
    page: 211,
  }),
  S({
    name: 'Shock Treatment',
    subtype: 'attack',
    tags: 'Electric',
    manaCost: '2',
    range: '30 feet',
    aiFavor: '2',
    baseDamage: '1d2 + Int Electric',
    upgrades:
      'R5: +1d2, may Stun instead of dealing damage · R10: +1d2, +1 Rank damage die (Electric) at end of round · R15: +1d2, ×5 damage at melee range',
    page: 212,
  }),
  S({
    name: 'Solsplash',
    subtype: 'attack',
    stat: 'con',
    tags: 'Fire · Favored: Druid',
    manaCost: '13',
    range: '30 feet',
    baseDamage: '1d8 + Con Fire',
    upgrades: 'R5: +1d8, +5 ft Splash · R10: +1d8, +10 ft Splash, Burned if 3+ slots lost · R15: +1d8, +15 ft Splash',
    page: 212,
  }),
  S({
    name: 'Soul Collector',
    subtype: 'attack',
    tags: 'Necrotic',
    manaCost: '4',
    range: '50 feet',
    aiFavor: '1',
    baseDamage: '1d4 + Int Necrotic',
    upgrades:
      'R5: +1d4, killing a foe of half your level+ gives +1 damage until a long rest (stacks up to Rank) · R10: +1d4, bonus lasts a week · R15: +1d4, lasts the whole floor',
    page: 212,
  }),
  S({
    name: 'Thunderlash',
    subtype: 'attack',
    tags: 'Sonic',
    manaCost: '12',
    range: '50 feet',
    baseDamage: '1d10 + Int Sonic',
    upgrades: 'R5: +1d10 · R10: +1d10, Armor-Piercing · R15: +1d10, can be a 15 ft Cone',
    page: 212,
  }),
  S({
    name: 'Torch',
    subtype: 'passive',
    manaCost: '1',
    range: 'Self',
    duration: 'Until you enter a saferoom or change floor',
    effect: 'Floating orb: bright light 20 ft, dim light 20 ft beyond',
    upgrades:
      'R5: move it up to 20 ft away · R10: up to 60 ft, double radius at will · R15: up to 100 ft, attach to a surface',
    page: 212,
  }),
  S({
    name: 'Tripper',
    subtype: 'passive',
    tags: 'Area of Effect',
    manaCost: 'None',
    range: '30 ft Burst radius',
    cooldown: '5 hours',
    limitations: 'Must be imbued onto something you wear; not traps with very specific triggers',
    effect: 'Sets off every movement, heat and weight-triggered trap in the area',
    upgrades: 'R5: + Intelligence to radius · R10: + Intelligence · R15: + Intelligence, damage taken counts as Splash',
    page: 213,
  }),
  S({
    name: 'Turn Undead',
    subtype: 'attack',
    stat: 'cha',
    tags: 'Area of Effect · Favored: Bard, Cleric & Paladin',
    manaCost: '9',
    range: '10 ft Cone',
    duration: '3 rounds',
    cooldown: '5 minutes',
    limitations: 'Not against Bosses',
    effect: 'One Cha-Opposed Spell Check vs Undead Mobs in the area; on Success they flee',
    upgrades:
      'R5: +5 ft Cone, 5 rounds · R10: +10 ft, 10 rounds · R15: +15 ft, 15 rounds, destroyed on Amazing Success',
    page: 213,
  }),
  S({
    name: 'Twinkle Toes',
    subtype: 'passive',
    tags: 'Intelligence',
    manaCost: '2',
    range: '5 feet',
    duration: 'Seconds equal to your Intelligence',
    effect: 'A pet or minion in range gets Move ×2',
    upgrades: 'R5: Move ×3 · R10: Move ×4 · R15: Move ×5',
    page: 213,
  }),
  S({
    name: 'Unnecessary Force',
    subtype: 'attack',
    tags: 'Force',
    manaCost: '13',
    range: '40 feet',
    baseDamage: '1d12 + Int Force',
    upgrades: 'R5: +1d12 · R10: +1d12, push 10 ft · R15: +1d12, push 15 ft',
    page: 213,
  }),
  S({
    name: 'Vine Porn',
    subtype: 'attack',
    stat: 'con',
    tags: 'Piercing · Favored: Druid',
    manaCost: '3',
    range: '20 feet',
    aiFavor: '1',
    baseDamage: '1d4 + Con Piercing',
    upgrades: 'R5: +1d4 · R10: +1d4, Armor-Piercing · R15: +1d4, ×4 damage on a Critical Hit',
    page: 213,
  }),
  S({
    name: 'Wall of Fire',
    subtype: 'passive',
    tags: 'Fire',
    manaCost: '15',
    range: '30 feet',
    duration: '2 rounds',
    effect: '30 ft long × 7 ft high × 2 ft thick wall of fire',
    baseDamage: '1d2 Fire per foot of wall passed through, and Burned',
    upgrades:
      'R5: +1d2, can be a ring, 5 rounds · R10: +1d2, 50 × 10 × 3 ft, 10 rounds · R15: +1d2, 100 × 20 × 5 ft, 15 rounds',
    page: 214,
  }),
  S({
    name: 'Water Breathing',
    subtype: 'passive',
    tags: 'Intelligence',
    manaCost: '2',
    range: 'Self',
    duration: 'Seconds equal to Intelligence × 3',
    effect: 'Breathe underwater',
    upgrades: 'R5: cast on others at 5 ft · R10: Swimming checks with Advantage · R15: everyone in a 15 ft Burst',
    page: 214,
  }),
  S({
    name: 'Web',
    subtype: 'attack',
    tags: 'Intelligence',
    manaCost: '6',
    range: '20 ft Cone',
    duration: '2 rounds',
    effect:
      'One Spell Attack Check vs each creature’s Evade in the cone (friends too); on Success it is Held, escape uses this Spell’s Rank',
    upgrades: 'R5: +5 ft Cone, 5 rounds · R10: +5 ft, 10 rounds · R15: +5 ft, 15 rounds',
    page: 214,
  }),
  S({
    name: 'Wilbur’s Slow-Build Fireblast',
    subtype: 'attack',
    tags: 'Fire',
    manaCost: '60',
    range: '50 feet',
    effect:
      'Can be held as a ring of fire until released; your next Attack Action must be this Spell. Anyone defusing the ring takes half damage',
    baseDamage: '1d8 + Int Fire, and Burned',
    upgrades: 'R5: +1d8, +1d8 per full day held · R10: +1d8, +5 ft Splash · R15: +1d8, +5 ft Splash',
    page: 214,
  }),
  S({
    name: 'Wisp Armor',
    subtype: 'passive',
    manaCost: '5',
    range: 'Self',
    duration: '5 minutes',
    cooldown: '5 minutes',
    effect: 'Magic damage against you is reduced to its Rank 1 base damage (1 die + Stat Mod); immune to Mind Control',
    upgrades: 'R5: 10 min · R10: 15 min · R15: 20 min',
    page: 214,
  }),
];
