// Attack Skills (Core Rulebook ch.4, Crawlers & Customization). Mechanical stats only;
// upgrades are written in compact notation. Page numbers refer to the Core Rulebook.
// Fields: subtype, attackType, stat (to-hit), range, aiFavor, limitations, cooldown, baseDamage, effect, upgrades, page

const melee = 'Melee (5 ft)';

export const WEAPONS = [
  // Animal crawler & pet strikes
  {
    name: 'Bite',
    subtype: 'animal',
    attackType: 'melee',
    stat: 'str',
    range: melee,
    limitations: 'Target needs an appendage you can clamp onto',
    baseDamage: '1d8 + Str Piercing',
    upgrades: 'R5: +1d8 · R10: +1d8, latch on and move with the foe · R15: +1d8, Woozy',
    page: 177,
  },
  {
    name: 'Back Claw',
    subtype: 'animal',
    attackType: 'melee',
    stat: 'str',
    range: melee,
    baseDamage: '1d6 + Str Slashing',
    upgrades: 'R5: +1d6 · R10: +1d6 · R15: +1d6, Blood Trail',
    page: 177,
  },
  {
    name: 'Slice Attack',
    subtype: 'animal',
    attackType: 'melee',
    stat: 'dex',
    range: melee,
    aiFavor: '1',
    baseDamage: '1d4 + Str Slashing',
    upgrades: 'R5: +1d4 · R10: +1d4 · R15: +2d4',
    page: 177,
  },
  // Bashing
  {
    name: 'Club',
    subtype: 'bashing',
    attackType: 'melee',
    stat: 'str',
    range: melee,
    baseDamage: '1d6 + Str Bludgeoning',
    upgrades: 'R5: +1d6 · R10: +1d6, Woozy · R15: +1d6, Take Down if target loses 3+ HB slots',
    page: 178,
  },
  {
    name: 'Improvised Weapons',
    subtype: 'bashing',
    attackType: 'melee',
    stat: 'str',
    range: melee,
    aiFavor: '1',
    limitations: 'Object weighs 1 lb up to your Strength in lb',
    baseDamage: '1d4 + Str Bludgeoning',
    upgrades: 'R5: +1d4, throw it up to Rank × 5 ft · R10: +1d4, first attack each combat with Advantage · R15: +1d4',
    page: 178,
  },
  {
    name: 'Warhammer',
    subtype: 'bashing',
    attackType: 'melee',
    stat: 'str',
    range: melee,
    limitations: 'Requires two hands to wield',
    baseDamage: '1d10 + Str Bludgeoning',
    upgrades: 'R5: +1d10 · R10: +1d10 · R15: +1d10, push target (your size or smaller) 15 ft',
    page: 178,
  },
  // Edged
  {
    name: 'Axe',
    subtype: 'edged',
    attackType: 'melee',
    stat: 'str',
    range: melee,
    baseDamage: '1d6 + Str Slashing',
    upgrades:
      'R5: +1d6 · R10: +1d6, free extra attack (Disadvantage) on a foe adjacent to you and the target · R15: +1d6, sever an arm on Amazing Success',
    page: 178,
  },
  {
    name: 'Dagger',
    subtype: 'edged',
    attackType: 'melee',
    stat: 'dex',
    range: melee,
    aiFavor: '1',
    baseDamage: '1d4 + Str Piercing',
    upgrades:
      'R5: +1d4, Armor-Piercing (ignores DR) · R10: +1d4, throw up to Rank × 5 ft · R15: +1d4, ×2 damage to a foe’s back',
    page: 178,
  },
  {
    name: 'Longsword',
    subtype: 'edged',
    attackType: 'melee',
    stat: 'str',
    range: melee,
    baseDamage: '1d8 + Str Slashing',
    upgrades: 'R5: +1d8 · R10: +1d8 · R15: +1d8, +1 Evade Buff',
    page: 178,
  },
  {
    name: 'Rapier',
    subtype: 'edged',
    attackType: 'melee',
    stat: 'dex',
    range: melee,
    baseDamage: '1d6 + Dex Piercing',
    upgrades: 'R5: +1d6 · R10: +1d6, +1 Evade Buff · R15: +1d6, +1 Evade Buff',
    page: 178,
  },
  // Hand-to-hand
  {
    name: 'Unarmed Combat',
    subtype: 'handToHand',
    attackType: 'melee',
    stat: 'str',
    range: melee,
    aiFavor: '1',
    limitations: 'Cannot choose a Damage Effect',
    baseDamage: '1d4 + Str Bludgeoning',
    upgrades: 'R5: +1d4 · R10: +1d4 · R15: +2d4',
    page: 179,
  },
  {
    name: 'Foot Soldier',
    subtype: 'handToHand',
    attackType: 'melee',
    stat: 'str',
    range: melee,
    aiFavor: '1 (only with no Damage Effect)',
    effect: 'Damage Effects: Powerful Strike or Smush',
    baseDamage: '1d4 + Str Bludgeoning',
    upgrades: 'R5: +1d4 · R10: +1d4 · R15: +1d4, Sore as Shit',
    page: 179,
  },
  {
    name: 'Noggin Nocker',
    subtype: 'handToHand',
    attackType: 'melee',
    stat: 'str',
    range: melee,
    aiFavor: '1 (only with no Damage Effect)',
    limitations: 'On Success you lose 1 HB slot',
    effect: 'Damage Effects: Skullcracker or Powerful Strike',
    baseDamage: '1d4 + Con Bludgeoning',
    upgrades: 'R5: +1d4, no self-damage · R10: +1d4, +1 Rank damage die · R15: +1d4, Woozy',
    page: 179,
  },
  {
    name: 'Pugilism',
    subtype: 'handToHand',
    attackType: 'melee',
    stat: 'dex',
    range: melee,
    aiFavor: '2 (only with no Damage Effect)',
    effect: 'Damage Effects: Dirty Fighting, Iron Punch or Powerful Strike',
    baseDamage: '1d2 + Str Bludgeoning',
    upgrades: 'R5: +2d2 · R10: +1d2 · R15: +1d2, free extra attack with Disadvantage',
    page: 179,
  },
  {
    name: 'Wrasslin’',
    subtype: 'handToHand',
    attackType: 'melee',
    stat: 'str',
    range: melee,
    aiFavor: '1 (only with no Damage Effect)',
    limitations: 'Requires two hands',
    effect:
      'On Success the target is Held until it spends an Action to escape; stop it with an Interrupt and a Wrasslin’ Str-Opposed check. Damage Effects: Choke Out, Dirty Fighting or Toss',
    baseDamage: '1d4 + Str Bludgeoning',
    upgrades: 'R5: keep Held at no Action cost (escape check with Disadvantage) · R10: +1d4 · R15: +1d4',
    page: 179,
  },
  // Hand-to-hand damage effects (passive)
  {
    name: 'Choke Out',
    subtype: 'damageEffect',
    effect: 'Wrasslin’ Damage Effect: ×2 total damage if the target is at 10% HB or less',
    upgrades: 'R5: works at 20% HB or less · R10: 40% HB, ×4 damage · R15: 80% HB, ×8 damage',
    page: 180,
  },
  {
    name: 'Dirty Fighting',
    subtype: 'damageEffect',
    effect: 'Pugilism or Wrasslin’ Damage Effect: target gains Woozy. Critical Fail on the attack: lose 1 Popularity',
    upgrades: 'R5: also The Taint · R10: also Blinded, no Popularity loss · R15: also a Minor Injury',
    page: 180,
  },
  {
    name: 'Iron Punch',
    subtype: 'damageEffect',
    effect: 'Pugilism Damage Effect: +1d2 base damage',
    upgrades: 'R5: +1 Rank damage die · R10: may Stun instead of rolling damage · R15: +1 Rank damage die and Stunned',
    page: 180,
  },
  {
    name: 'Powerful Strike',
    subtype: 'damageEffect',
    cooldown: '30 hours',
    effect: 'Foot Soldier, Noggin Nocker or Pugilism Damage Effect: multiply the base damage dice result by your Rank',
    upgrades: 'R5: cooldown 10 h · R10: cooldown 5 h · R15: cooldown 2 h',
    page: 180,
  },
  {
    name: 'Skullcracker',
    subtype: 'damageEffect',
    effect: 'Noggin Nocker Damage Effect: +1d4 base damage vs targets your size',
    upgrades: 'R5: +1d4 more · R10: +1 Rank damage die and Stunned · R15: +1 Rank damage die and Blood Trail',
    page: 180,
  },
  {
    name: 'Smush',
    subtype: 'damageEffect',
    limitations: 'Only vs targets at 20% HB or less',
    cooldown: 'Once per round',
    effect: 'Foot Soldier Damage Effect: ×2 total damage',
    upgrades: 'R5: 30% HB, ×3 · R10: no cooldown · R15: 40% HB, ×4',
    page: 181,
  },
  {
    name: 'Toss',
    subtype: 'damageEffect',
    effect:
      'Wrasslin’ Damage Effect: +1d8 + Str Bludgeoning, ends Held, throw the target 5 ft per 5 Ranks (min 5 ft). Only smaller foes',
    upgrades: 'R5: foes up to your size · R10: one size larger · R15: +1d8, two sizes larger',
    page: 181,
  },
  // Ranged
  {
    name: 'Bow',
    subtype: 'ranged',
    attackType: 'ranged',
    stat: 'dex',
    range: '100 feet',
    limitations: 'Requires two hands; needs ammunition',
    baseDamage: '1d6 + Str Piercing',
    upgrades: 'R5: +1d6 · R10: +1d6, +1 Rank damage die · R15: +1d6, Blood Trail',
    page: 181,
  },
  {
    name: 'Crossbow',
    subtype: 'ranged',
    attackType: 'ranged',
    stat: 'dex',
    range: '50 feet',
    limitations: 'Requires two hands; needs ammunition',
    cooldown: 'Once per round',
    baseDamage: '1d8 Piercing',
    upgrades: 'R5: +1d8 · R10: +1d8, Blood Trail · R15: +1d8, range 100 ft',
    page: 181,
  },
  {
    name: 'Handgun',
    subtype: 'ranged',
    attackType: 'ranged',
    stat: 'dex',
    range: '150 feet',
    limitations: 'Needs ammunition; reload (1 Action) after a Major Fail or worse',
    baseDamage: '1d8 Piercing',
    upgrades: 'R5: +1d8 · R10: +1d8 · R15: +1d8, Staggered',
    page: 181,
  },
  {
    name: 'Javelin',
    subtype: 'ranged',
    attackType: 'ranged',
    stat: 'dex',
    range: '40 feet',
    baseDamage: '1d8 + Str Piercing',
    upgrades: 'R5: +1d8 · R10: +1d8, Armor-Piercing · R15: +1d8, range + Strength score in ft',
    page: 182,
  },
  {
    name: 'Shotgun',
    subtype: 'ranged',
    attackType: 'ranged',
    stat: 'dex',
    range: '30 feet',
    limitations: 'Requires two hands; needs ammunition; reload after a Major Fail or worse',
    baseDamage: '1d10 Piercing',
    upgrades: 'R5: +1d10 · R10: +1d10 · R15: +1d10, +5 ft Splash',
    page: 182,
  },
  {
    name: 'Shuriken',
    subtype: 'ranged',
    attackType: 'ranged',
    stat: 'dex',
    range: '30 feet',
    aiFavor: '1',
    baseDamage: '1d4 + Str Piercing',
    upgrades:
      'R5: +1d4, range 40 ft · R10: +1d4, free extra attack with Disadvantage · R15: +1d4, another free extra attack',
    page: 182,
  },
  {
    name: 'Slingshot',
    subtype: 'ranged',
    attackType: 'ranged',
    stat: 'dex',
    range: '30 feet',
    aiFavor: '2',
    limitations: 'Requires two hands',
    baseDamage: '1d2 + Str Bludgeoning',
    upgrades: 'R5: +1d2, range + Strength score in ft · R10: +1d2, +1 Rank damage die · R15: +1d2, +1 Rank damage die',
    page: 182,
  },
  // Reach
  {
    name: 'Herding Weapons',
    subtype: 'reach',
    attackType: 'melee',
    stat: 'str',
    range: '10 feet',
    aiFavor: '1',
    limitations: 'Requires two hands',
    baseDamage: '1d4 + Str Bludgeoning',
    upgrades: 'R5: +1d4, slide the target 5 ft · R10: +1d4, Sling attack at 50 ft using Dex · R15: +1d4, Take Down',
    page: 182,
  },
  {
    name: 'Lance',
    subtype: 'reach',
    attackType: 'melee',
    stat: 'str',
    range: '10 feet',
    limitations: 'Must be mounted; not with Attack of Opportunity or Zone of Control',
    baseDamage: '1d12 + Str Piercing',
    upgrades: 'R5: +1d12 · R10: +1d12, +1 per 10 ft your mount moved · R15: +1d12, + your mount’s size',
    page: 182,
  },
  {
    name: 'Polearm',
    subtype: 'reach',
    attackType: 'melee',
    stat: 'str',
    range: '10 feet',
    limitations: 'Requires two hands',
    baseDamage: '1d8 + Str Piercing',
    upgrades: 'R5: +1d8 · R10: +1d8, +1 Zone of Control Rank · R15: +1d8, +1 Zone of Control Rank',
    page: 183,
  },
  {
    name: 'Quarterstaff',
    subtype: 'reach',
    attackType: 'melee',
    stat: 'str',
    range: '10 feet',
    limitations: 'Requires two hands',
    baseDamage: '1d6 + Str Bludgeoning',
    upgrades: 'R5: +1d6 · R10: +1d6, +1 Evade Buff · R15: +1d6, +1 Evade Buff',
    page: 183,
  },
];
